### ISSUE TITLE
Installing without composer

### ISSUE THREAD

**Issue by CodeSmith32** [rybakit/msgpack.php#29]
I do not have composer, and am simply hoping to use this code as a drop-in polyfill / substitute for the PHP msgpack extension (which I could not get to work) for my dev environment.

How would I go about installing this without composer?

TIA

**Comment by rybakit** [comment]
> How would I go about installing this without composer?

You can install it the same way you did before composer existed: copy src files somewhere and include them in your script (or write a [PSR-4 compliant loader](https://www.php-fig.org/psr/psr-4/examples/)). A quick search on the internet shows that there are even [online tools](https://php-download.com/package/rybakit/msgpack) that can do it for you.
